import { toCsv } from "../../lib/csv";

export type ClosingDay = { businessDate:string; openingCashMinor:number; expectedCashMinor:number; countedCashMinor:number|null; differenceMinor:number|null; openedByName:string; closedByName:string|null; openedAt:string; closedAt:string|null; notes:string };
const headers=["Business date","Opening cash (SAR)","Expected cash (SAR)","Counted cash (SAR)","Difference (SAR)","Opened by","Closed by","Closed at","Notes"] as const;
const value=(minor:number|null)=>minor===null?"":(minor/100).toFixed(2);
const rows=(days:ClosingDay[])=>days.map(day=>[day.businessDate,value(day.openingCashMinor),value(day.expectedCashMinor),value(day.countedCashMinor),value(day.differenceMinor),day.openedByName,day.closedByName??"",day.closedAt??"",day.notes]);
function download(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.click();URL.revokeObjectURL(url);}
export function exportBusinessDaysCsv(days:ClosingDay[],filename:string){download(new Blob(["\uFEFF",toCsv(headers,rows(days))],{type:"text/csv;charset=utf-8"}),`${filename}.csv`);}
export function exportBusinessDaysExcel(days:ClosingDay[],filename:string){const escape=(value:unknown)=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");const allRows=[[...headers],...rows(days)];const xml=`<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Header"><Font ss:Bold="1"/><Interior ss:Color="#DDEBE8" ss:Pattern="Solid"/></Style></Styles><Worksheet ss:Name="Daily closing"><Table>${allRows.map((row,index)=>`<Row>${row.map(cell=>`<Cell${index===0?' ss:StyleID="Header"':""}><Data ss:Type="String">${escape(cell)}</Data></Cell>`).join("")}</Row>`).join("")}</Table></Worksheet></Workbook>`;download(new Blob(["\uFEFF",xml],{type:"application/vnd.ms-excel;charset=utf-8"}),`${filename}.xml`);}
export async function exportBusinessDaysPdf(days:ClosingDay[],filename:string,range:string){const [{default:jsPDF},{default:autoTable}]=await Promise.all([import("jspdf"),import("jspdf-autotable")]);const document=new jsPDF({orientation:"landscape"});document.setFontSize(16);document.text("Daily opening and closing report",14,16);document.setFontSize(9);document.text(range,14,22);autoTable(document,{startY:27,head:[["Date","Opening","Expected","Counted","Difference","Opened by","Closed by","Notes"]],body:days.map(day=>[day.businessDate,`SAR ${value(day.openingCashMinor)}`,`SAR ${value(day.expectedCashMinor)}`,`SAR ${value(day.countedCashMinor)}`,`SAR ${value(day.differenceMinor)}`,day.openedByName,day.closedByName??"",day.notes]),styles:{fontSize:8,cellPadding:2},headStyles:{fillColor:[29,78,216]}});document.save(`${filename}.pdf`);}
