"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../../app/client";
import { exportBusinessDaysCsv, exportBusinessDaysExcel, exportBusinessDaysPdf, type ClosingDay } from "../../app/lib/business-day-export";
import "./daily-closing-report.css";

type Locale="en"|"ar";
type Result={recent:ClosingDay[];total:number;page:number;pageSize:number;range:{from:string;to:string}};
const currentMonth=()=>new Date(Date.now()+3*60*60_000).toISOString().slice(0,7);
const money=(minor:number|null)=>new Intl.NumberFormat("en-SA",{style:"currency",currency:"SAR"}).format((minor??0)/100);
const t=(locale:Locale,en:string,ar:string)=>locale==="ar"?ar:en;

export function DailyClosingReport({locale}:{locale:Locale}){
  const [mode,setMode]=useState<"month"|"range">("month"),[month,setMonth]=useState(currentMonth),[from,setFrom]=useState(""),[to,setTo]=useState("");
  const [applied,setApplied]=useState({mode:"month" as "month"|"range",month:currentMonth(),from:"",to:""});
  const [result,setResult]=useState<Result|null>(null),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(""),[exporting,setExporting]=useState("");
  const query=useMemo(()=>{const values=new URLSearchParams({page:String(page),pageSize:"25"});if(applied.mode==="month")values.set("month",applied.month);else {values.set("from",applied.from);values.set("to",applied.to);}return values;},[applied,page]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{setResult(await api<Result>(`/api/business-day?${query}`));}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load daily report");}finally{setLoading(false);}},[query]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  function apply(){if(mode==="range"&&(!from||!to||from>to)){setError(t(locale,"Choose a valid start and end date.","اختر تاريخ بداية ونهاية صحيحين."));return;}setPage(1);setApplied({mode,month,from,to});}
  async function exportReport(kind:"csv"|"xlsx"|"pdf"){setExporting(kind);setError("");try{const values=new URLSearchParams(query);values.set("page","1");values.set("pageSize","1000");const full=await api<Result>(`/api/business-day?${values}`);if(full.total>1000)throw new Error("Export is limited to 1,000 days. Narrow the date range.");const filename=`daily-opening-closing-${full.range.from}-${full.range.to}`;if(kind==="csv")exportBusinessDaysCsv(full.recent,filename);if(kind==="xlsx")exportBusinessDaysExcel(full.recent,filename);if(kind==="pdf")await exportBusinessDaysPdf(full.recent,filename,`${full.range.from} to ${full.range.to}`);}catch(caught){setError(caught instanceof Error?caught.message:"Export failed");}finally{setExporting("");}}
  const totalDifference=(result?.recent??[]).reduce((sum,day)=>sum+(day.differenceMinor??0),0);
  return <section className="daily-report"><header><div><p>{t(locale,"CASH SESSION REPORT","تقرير جلسات النقد")}</p><h1>{t(locale,"Daily opening & closing","الافتتاح والإغلاق اليومي")}</h1><span>{t(locale,"Review closed shop days by month or a custom date range.","راجع أيام المتجر المغلقة حسب الشهر أو نطاق تاريخ مخصص.")}</span></div><div className="daily-export">{(["csv","xlsx","pdf"] as const).map(kind=><button key={kind} disabled={Boolean(exporting)||!result?.recent.length} onClick={()=>void exportReport(kind)}>{exporting===kind?t(locale,"Preparing…","جارٍ التحضير…"):kind==="xlsx"?"Excel":kind.toUpperCase()}</button>)}</div></header>
    <div className="daily-filters"><label><span>{t(locale,"View","العرض")}</span><select value={mode} onChange={event=>setMode(event.target.value as "month"|"range")}><option value="month">{t(locale,"Month","شهر")}</option><option value="range">{t(locale,"Date range","نطاق تاريخ")}</option></select></label>{mode==="month"?<label><span>{t(locale,"Month","الشهر")}</span><input type="month" value={month} onChange={event=>setMonth(event.target.value)}/></label>:<><label><span>{t(locale,"From","من")}</span><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label><span>{t(locale,"To","إلى")}</span><input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></>}<button onClick={apply}>{t(locale,"Apply","تطبيق")}</button></div>
    {error&&<p className="daily-error" role="alert">{error}</p>}
    <div className="daily-summary"><span><small>{t(locale,"Closed days","الأيام المغلقة")}</small><b>{result?.total??0}</b></span><span><small>{t(locale,"Expected cash","النقد المتوقع")}</small><b>{money((result?.recent??[]).reduce((sum,day)=>sum+day.expectedCashMinor,0))}</b></span><span><small>{t(locale,"Difference on this page","الفرق في هذه الصفحة")}</small><b className={totalDifference===0?"":"difference"}>{money(totalDifference)}</b></span></div>
    <div className="daily-table-wrap" aria-busy={loading}><table><thead><tr><th>{t(locale,"Date","التاريخ")}</th><th>{t(locale,"Opening","الافتتاح")}</th><th>{t(locale,"Expected","المتوقع")}</th><th>{t(locale,"Counted","المعدود")}</th><th>{t(locale,"Difference","الفرق")}</th><th>{t(locale,"Opened by","فتح بواسطة")}</th><th>{t(locale,"Closed by","أغلق بواسطة")}</th><th>{t(locale,"Notes","ملاحظات")}</th></tr></thead><tbody>{result?.recent.map(day=><tr key={day.businessDate}><td><b>{day.businessDate}</b><small>{day.closedAt?new Intl.DateTimeFormat(locale==="ar"?"ar-SA":"en-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(new Date(day.closedAt)):""}</small></td><td>{money(day.openingCashMinor)}</td><td>{money(day.expectedCashMinor)}</td><td>{money(day.countedCashMinor)}</td><td className={(day.differenceMinor??0)===0?"":"difference"}>{money(day.differenceMinor)}</td><td>{day.openedByName}</td><td>{day.closedByName??"-"}</td><td>{day.notes||"-"}</td></tr>)}{!loading&&!result?.recent.length&&<tr><td colSpan={8}>{t(locale,"No closed days match this filter.","لا توجد أيام مغلقة تطابق هذا الفلتر.")}</td></tr>}</tbody></table></div>
    {result&&result.total>result.pageSize&&<footer><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>{t(locale,"Previous","السابق")}</button><span>{page} / {Math.ceil(result.total/result.pageSize)}</span><button disabled={page*result.pageSize>=result.total} onClick={()=>setPage(value=>value+1)}>{t(locale,"Next","التالي")}</button></footer>}
  </section>;
}
